package:
  name: cronomaxrf
  version: 0.0.3
source:
  sha256: ad1c97696fc16f926012455ed31a0859747ea192bed695b992cbfa5c65f571b1
  url: https://files.pythonhosted.org/packages/6f/ca/db870613a293c0d3ff22437cc60c9efb5961a7de78a1ed6616202138517b/cronomaxrf-0.0.3.tar.gz
about:
  dev_url: https://fligt.github.io
  doc_url: https://fligt.github.io
  home: https://fligt.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python package to read and convert the Crono MA-XRF HDF5 data file format
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - fligt
requirements:
  host:
  - pip
  - python
  - packaging
  - h5py
  - dask
  - zarr
  - matplotlib
  - numpy
  - IPython
  - b2sdk
  - dask_ndfilters
  run:
  - pip
  - python
  - packaging
  - h5py
  - dask
  - zarr
  - matplotlib
  - numpy
  - IPython
  - b2sdk
  - dask_ndfilters
test:
  imports:
  - cronomaxrf
